// export const cardInfo = [
//   {
//     id: 1,
//     name: "M0231",
//     breed: "Pomeranian White",
//     gender: "Male",
//     age: "02 months",
//     price: "6.900.000 VND",
//     // image: "/images/cat1.jpg",
//   },
//   {
//     id: 2,
//     name: "M0232",
//     breed: "Tabby Cat",
//     gender: "Male",
//     age: "02 months",
//     price: "6.900.000 VND",
//     // image: "/images/cat2.jpg",
//   },
//   {
//     id: 3,
//     name: "M0233",
//     breed: "White Persian",
//     gender: "Male",
//     age: "02 months",
//     price: "6.900.000 VND",
//     // image: "/images/cat3.jpg",
//   },
//   {
//     id: 4,
//     name: "M0234",
//     breed: "Calico Cat",
//     gender: "Male",
//     age: "02 months",
//     price: "6.900.000 VND",
//     // image: "/images/cat4.jpg",
//   },
//   {
//     id: 5,
//     name: "M0235",
//     breed: "Bernese Mountain",
//     gender: "Male",
//     age: "02 months",
//     price: "6.900.000 VND",
//     // image: "/images/dog1.jpg",
//   },
//   {
//     id: 6,
//     name: "M0236",
//     breed: "Border Collie",
//     gender: "Male",
//     age: "02 months",
//     price: "6.900.000 VND",
//     // image: "/images/dog2.jpg",
//   },
//   {
//     id: 7,
//     name: "M0237",
//     breed: "Golden Retriever",
//     gender: "Male",
//     age: "02 months",
//     price: "6.900.000 VND",
//     // image: "/images/dog3.jpg",
//   },
//   {
//     id: 8,
//     name: "M0238",
//     breed: "Puppy Mix",
//     gender: "Male",
//     age: "02 months",
//     price: "6.900.000 VND",
//     // image: "/images/dog4.jpg",
//   },
// ];
