import * as images from "@/assets/images/images";

export const productsData = [
  {
    id: 1,
    name: "Dog Food Premium",
    price: "$20",
    category: "Food",
    brand: "NutriPet",
    description: "Premium dog food packed with essential nutrients, vitamins, and minerals to keep your furry friend healthy and happy. Made with real meat and no artificial preservatives.",
    features: ["Grain-free", "High Protein", "All Life Stages", "No Artificial Colors"],
    details: "Size: 5 kg | Flavor: Chicken & Sweet Potato",
    rating: 4.8,
    reviewsCount: 156,
    mainImage: images.product1,
    gallery: [images.product1],
  },
  {
    id: 2,
    name: "Cat Scratcher",
    price: "$15",
    category: "Toys",
    brand: "CatnipDreams",
    description: "Keep your cat entertained and your furniture safe with this durable corrugated cardboard scratcher. Includes a packet of premium catnip to entice your feline friend.",
    features: ["Recyclable", "Reversible Design", "Includes Catnip"],
    details: "Material: Corrugated Cardboard | Dimensions: 45 x 20 x 5 cm",
    rating: 4.5,
    reviewsCount: 89,
    mainImage: images.product2,
    gallery: [images.product2],
  },
  {
    id: 3,
    name: "Pet Shampoo",
    price: "$10",
    category: "Grooming",
    brand: "SparklePet",
    description: "Gentle tearless formula for dogs and cats. Cleans, conditions, detangles, and moisturizes your pet's fur, leaving it smelling fresh and clean.",
    features: ["Oatmeal & Aloe Vera", "Tearless", "Paraben-Free", "Hypoallergenic"],
    details: "Volume: 500 ml | Scent: Lavender",
    rating: 4.7,
    reviewsCount: 210,
    mainImage: images.product3,
    gallery: [images.product3],
  },
  {
    id: 4,
    name: "Pet Carrier",
    price: "$30",
    category: "Travel",
    brand: "SafeJourney",
    description: "Sturdy travel carrier for small dogs and cats. Features breathable mesh windows, a cozy machine-washable interior pad, and an adjustable shoulder strap.",
    features: ["Airline Approved", "Breathable Mesh", "Water-Resistant", "Padded Strap"],
    details: "Max Weight: 15 lbs | Dimensions: 17 x 10 x 11 inches",
    rating: 4.6,
    reviewsCount: 342,
    mainImage: images.product4,
    gallery: [images.product4],
  },
  {
    id: 5,
    name: "Dog Leash",
    price: "$12",
    category: "Accessories",
    brand: "Walkies",
    description: "Heavy-duty reflective dog leash with a comfortable padded handle. Built to withstand strong pullers and ensure visibility during night walks.",
    features: ["Reflective Threads", "Padded Handle", "Tangle-Free Swivel Hook", "Heavy Duty"],
    details: "Length: 5 feet | Material: Nylon",
    rating: 4.9,
    reviewsCount: 512,
    mainImage: images.product5,
    gallery: [images.product5],
  },
  {
    id: 6,
    name: "Cat Toy",
    price: "$8",
    category: "Toys",
    brand: "PlayfulWhiskers",
    description: "Interactive feather wand toy designed to stimulate your cat's natural hunting instincts. Provides hours of active play and exercise.",
    features: ["Flexible Wand", "Replaceable Feathers", "Bells Attached"],
    details: "Wand Length: 36 inches | Material: Carbon fiber and natural feathers",
    rating: 4.4,
    reviewsCount: 125,
    mainImage: images.product6,
    gallery: [images.product6],
  },
  {
    id: 7,
    name: "Pet Bed",
    price: "$25",
    category: "Furniture",
    brand: "CozyPaws",
    description: "Ultra-soft plush pet bed for cats and small dogs. Orthopedic support with raised rims to provide a sense of security and head/neck support.",
    features: ["Machine Washable", "Non-Slip Bottom", "Orthopedic Foam", "Self-Warming"],
    details: "Diameter: 23 inches | Ideal for pets up to 25 lbs",
    rating: 4.8,
    reviewsCount: 430,
    mainImage: images.product7,
    gallery: [images.product7],
  },
  {
    id: 8,
    name: "Pet Bowl",
    price: "$7",
    category: "Feeding",
    brand: "DineRight",
    description: "High-quality stainless steel pet bowl with a non-slip silicone base. Rust-resistant, easy to clean, and perfect for dry kibble, wet food, treats, or water.",
    features: ["Stainless Steel", "Non-Slip Base", "Dishwasher Safe", "Rust-Resistant"],
    details: "Capacity: 32 oz | Base Diameter: 8.5 inches",
    rating: 4.7,
    reviewsCount: 280,
    mainImage: images.product8,
    gallery: [images.product8],
  }
];
